export const departments = [
  'Computer Science',
  'Software Engineering',
  'Information Technology',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Business Administration',
  'Commerce',
  'Economics',
  'Finance',
  'Marketing',
  'Human Resource Management',
  'Medicine (MBBS)',
  'Dentistry (BDS)',
  'Pharmacy',
  'Nursing',
  'Physiotherapy',
  'Law',
  'Architecture',
  'Fine Arts',
  'Design',
  'Media Studies',
  'Mass Communication',
  'English',
  'Education',
  'Psychology',
  'Sociology',
  'International Relations',
  'Political Science',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Other'
];

export const semesters = [1, 2, 3, 4, 5, 6, 7, 8];
